---
title: "Teaching Bayesian Statistics at the Undergraduate Level\n\nBayesian Foundations"
subtitle: "USCOTS workshop"
author: "Miles Ott"
date: "2021-06-24"
output:
  xaringan::moon_reader:
    css: style.css
    lib_dir: libs
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>`
---

---

class: middle 

## Bayesian Foundations Chapters

1. The Big (Bayesian) Picture

--

2. Bayes' Rule

--

3. The Beta-Binomial Bayesian Model

--

4. Balance and Sequentiality in Bayesian Analyses

--

5. Conjugate Families



---

class: middle 

## Chapter 1 Goals

- Learn to think like a Bayesian

--

- Explore the foundations of a Bayesian data analysis and how they contrast with the frequentist alternative

--

- Learn a little bit about the history of the Bayesian philosophy

---

class: middle 

## Chapter 2 Goals

--

- Explore foundational probability tools such as marginal, conditional, and joint probability models and the Binomial model

--

- Conduct your first formal Bayesian analysis! You will construct your first prior and likelihood models and, from these, construct your first posterior models via Bayes’ Rule

--

- Practice your Bayesian grammar. Practice the formal notation and terminology central to Bayesian grammar

--

- Simulate Bayesian models. Simulation is integral to building intuition for and supporting Bayesian analyses. You’ll conduct your first simulation, using the R statistical software, in this chapter

---

class: middle 

## Chapter 3 Goals

--

- Utilize and tune continuous priors. You will learn how to interpret and tune a continuous Beta prior model to reflect your prior information about  $\pi$

--

- Interpret and communicate features of prior and posterior models using properties such as mean, mode, and variance

--

- Construct the fundamental Beta-Binomial model for proportion $\pi$

---

class: middle 

## Chapter 4 Goals

--

- Explore the balanced influence of the prior and data on the posterior. You will see how our choice of prior model, the features of our data, and the delicate balance between them can impact the posterior model

--

- Perform sequential Bayesian analysis. You will explore one of the coolest features of Bayesian analysis: how a posterior model evolves as it’s updated with new data

---

class: middle 

## Chapter 5 Goals

--

- Practice building Bayesian models. You will build Bayesian models by practicing how to recognize kernels and make use of proportionality

--

- Familiarize yourself with conjugacy. You will learn about what makes a prior conjugate and why this is a helpful property

---